import './App.css';
import { SimpsonComponent } from "./components/simpsoncomponent";
import {FamilyComponent} from "./components/familycomponent";


function App() {
  return (
      <div className="App">
          <FamilyComponent
            familyitem={'Simpsons Family'}
            familypic={'https://upload.wikimedia.org/wikipedia/en/0/0d/Simpsons_FamilyPicture.png'}
            familydesc={'The Simpsons are a family who live at 742 Evergreen Terrace in the town of Springfield in the United States. The state in which in this town is located is never specified, however they do have snow and sometimes wear sweaters in the fall. It\'s a running joke in the show to be as vague and ambiguous as possible whenever hinting at which U.S. state the town of Springfield might be located in. Homer, the father, works as a safety inspector at the Springfield Nuclear Power Plant, a position at odds with his careless, buffoonish personality. He is married to Marge Simpson, a stereotypical American housewife and mother. They have three children: Bart, a ten-year-old troublemaker; Lisa, an eight-year-old child prodigy; and Maggie, a toddler who rarely speaks, but communicates by sucking on a pacifier. The family owns a dog, Santa\'s Little Helper, and a cat, Snowball II. Both pets have had starring roles in several seasons. Despite the passing of yearly milestones such as holidays or birthdays, the Simpsons do not physically age and still appear as they did at the end of the 1980s. Although the family is dysfunctional, many episodes examine their relationships and bonds with each other and they are often shown to care about one another.'}
          />


        <SimpsonComponent
            itemname={'Homer'}
            pics={'https://upload.wikimedia.org/wikipedia/en/0/02/Homer_Simpson_2006.png'}
            desc={'Homer Jay Simpson (voiced by Dan Castellaneta) is the protagonist of the show and the father of the Simpson family. He embodies several American working class stereotypes: he is crude, overweight, incompetent, clumsy, thoughtless and a borderline alcoholic. He has occasionally displayed flashes of great intellect and fitness whenever the situation calls for it, and an integrity reflecting his own values, including a fierce devotion to and protectiveness of his family. His voice started out as an impression of Walter Matthau but eventually evolved into a more robust voice during the second and third season of the half-hour show, allowing Homer to cover a fuller range of emotions. Homer has since become one of the most influential fictional characters and has been described by the UK newspaper The Sunday Times as the greatest comedic creation of modern time.[19] He has inspired an entire line of merchandise, and his catchphrase, the annoyed grunt "D\'oh!", has been included in the Oxford English Dictionary. During the production of the episode Insane Clown Poppy the writers toyed with the idea of giving Homer a long lost illegitimate biological daughter, but when the shows showrunner and writer Mike Scully, as well as Matt Groening rejected the idea, the writers changed the story so the clown Krusty would be the one who finds he has a lost daughter.'}
        />
          <SimpsonComponent
              itemname={'Marge'}
              pics={'https://upload.wikimedia.org/wikipedia/ru/0/0b/Marge_Simpson.png'}
              desc={'Marjorie Jacqueline "Marge" Simpson (née Bouvier, voiced by Julie Kavner) is the well-meaning and extremely patient wife of Homer and mother of Bart, Lisa and Maggie. She often acts as the voice of reason, but displays exaggerated behavior traits of stereotypical mothers and takes the blatant dysfunctionality of her family for granted,unlike the other family members, who are aware that they are eccentric. Her most notable physical feature is her blue hair, styled into an improbably high beehive. Julie Kavner received a Primetime Emmy Award in 1992 for voicing Marge in the episode "I Married Marge". For her performance in The Simpsons Movie, Kavner received a nomination for "Best Voice Acting in an Animated Feature" at the 2007 Annie Awards, but lost to Ian Holm in Ratatouille. Kavner\'s emotional performance in the movie got positive reviews and one critic said she "gave what must be the most heartfelt performance ever"] Part of Kavner\'s contract says that she will never have to promote The Simpsons on video because she does not want to "destroy the illusion for children". In 2008, CityNews published an article entitled "Top 10 Greatest TV Moms of All Time", and placed Marge in eighth spot.\n'}
              />
          <SimpsonComponent
              itemname={'Bart'}
              pics={'https://upload.wikimedia.org/wikipedia/en/a/aa/Bart_Simpson_200px.png'}
              desc={'Bartholomew JoJo "Bart" Simpson (voiced by Nancy Cartwright) is the eldest child and only son in the family—at age 10. Bart\'s most prominent character traits are his mischievousness, rebelliousness, disrespect for authority and sharp wit. During the first two seasons of The Simpsons, Bart was the show\'s main character. The name "Bart" is an anagram of the word "brat". Groening conceived Bart as an extreme version of the typical misbehaving child character, merging all of the extreme traits of characters such as Tom Sawyer and Huckleberry Finn into one person.Groening\'s older brother Mark provided most of the inspiration for Bart. Bart\'s catchphrase "Eat My Shorts" was an ad-lib by Cartwright in one of the original table readings, harking back to an incident when she was at college. In 1998, Time magazine selected Bart as 46th of the 100 most influential people of the 20th century, and the only fictional character to make the list. He had previously appeared on the cover of the December 31, 1990 edition. Bart is rebellious and frequently escapes without punishment, which led some parents\' groups and conservative spokespeople to believe he provided a poor role model for children. This prompted George H. W. Bush to rally, "We\'re going to keep trying to strengthen the American family. To make them more like the Waltons and less like the Simpsons." Bart, and other Simpsons characters, have appeared in numerous television commercials for Nestlé\'s Butterfinger candy bars from 1990 to 2001, with the slogan "Nobody better lay a finger on my Butterfinger!"'}
              />
          <SimpsonComponent
              itemname={'Lisa'}
              pics={'https://upload.wikimedia.org/wikipedia/en/e/ec/Lisa_Simpson.png'}
              desc={'Lisa Marie Simpson (voiced by Yeardley Smith) is the eldest daughter and middle child of the family. She is an extremely intelligent 8-year-old girl, one of the most intelligent characters on the show. Lisa\'s political convictions are generally socially liberal. She is a vegetarian, and a supporter of the Free Tibet movement, and while still supportive of the Christian church in which she was raised, Lisa became a practicing Buddhist following her decision to follow the Noble Eightfold Path. She is musically proficient on the saxophone; besides the occasional riff during the opening credit sequence Carole King\'s Jazzman and Gerry Rafferty\'s Baker Street have been prominently placed during episodes. In the Tracey Ullman Show shorts, Lisa was more of a "female Bart" and was equally mischievous. As the series progressed, Lisa began to develop into a more intelligent and more emotional character with "Krusty Gets Busted" being one of the first episodes where her true intelligence is fully shown. When she was a baby, Bart started out not liking her, although he became nicer to her after Marge pointed out that Lisa loves him. Her first word was "Bart", with Bart happily teaching her more names. Many episodes focusing on Lisa have an emotional nature, the first one being "Moaning Lisa". The idea for the episode was pitched by James L. Brooks, who had wanted to do an emotional episode where Lisa is sad because the show had done a lot of "jokey episodes". In 2001 Lisa received a special "board of directors Ongoing Commitment Award" at the Environmental Media Awards. "Lisa the Vegetarian", an episode from the seventh season, won both an Environmental Media Award for "Best Television Episodic Comedy" and a Genesis Award for "Best Television Comedy Series, Ongoing Commitment". In Japan, the broadcasters of the series found they were able to turn the apparent viewer dislike of the series around by focusing marketing attention on Lisa. Lisa\'s well-intended but ill-fated struggles to be a voice of reason and a force of good in her family and city struck a chord with the Japanese.'}
              />
          <SimpsonComponent
              itemname={'Maggie'}
              pics={'https://upload.wikimedia.org/wikipedia/en/9/9d/Maggie_Simpson.png'}
              desc={'Margaret Evelyn Lenny "Maggie" Simpson is the youngest of the five main family members and is almost always seen as a baby. She has blonde spiked hair like Lisa. Her first word was "daddy", shown at one point after Homer tucks her in. She is almost 2 years old and still uses a pacifier despite teething, although this was mentioned in a Treehouse of Horror episode ("Starship Poopers") and is not considered canon. She was quite prominent in the Tracey Ullman Show shorts, often being featured alongside Bart and Lisa but has since become the least seen and heard of the five main Simpsons. It has been revealed that Maggie has outstanding artistic and academic abilities, much like her sister Lisa. The episodes taking place in the future often show her as some kind of businesswoman.'}
              />
      </div>
  )
}

export default App;
